#cloud-config

coreos:
  units:
    - name: locksmithd.service
      mask: true
    - name: scripts.service
      command: start
      content: |
        [Unit]
        Description=Configuration scripts
        Requires=network-online.target
        After=network-online.target

        [Service]
        EnvironmentFile=/etc/farm-environment
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/rm -rf /tmp/tf-module
        ExecStart=/usr/bin/git clone --depth 1 $${CONFIG_URL} /tmp/tf-module
        TimeoutStartSec=0
    - name: data-storage.service
      command: start
      content: |
        [Unit]
        Description=Local storage
        Requires=scripts.service
        After=scripts.service

        [Service]
        EnvironmentFile=/etc/farm-environment
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/tmp/tf-module/scripts/disk-mgmt start $${MACHINE_TYPE}
        ExecStop=/tmp/tf-module/scripts/disk-mgmt stop $${MACHINE_TYPE}
        TimeoutStartSec=0
    - name: glusterfs.service
      command: start
      content: |
        [Unit]
        Description=Shared storage
        Requires=scripts.service data-storage.service
        After=scripts.service data-storage.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/tmp/tf-module/scripts/glusterfs-mgmt start
        ExecStop=/tmp/tf-module/scripts/glusterfs-mgmt stop
        TimeoutStartSec=0
    - name: git-daemon.service
      command: start
      content: |
        [Unit]
        Description=Git Daemon
        After=docker.service data-storage.service glusterfs.service
        Requires=docker.service data-storage.service glusterfs.service

        [Service]
        ExecStartPre=-/usr/bin/docker kill %p
        ExecStartPre=-/usr/bin/docker rm %p
        ExecStartPre=/usr/bin/docker pull quay.io/swi-infra/git-daemon
        ExecStart=/usr/bin/docker run \
                              --name %p \
                              --rm \
                              --publish 9418:9418 \
                              --volume /storage/git-oss:/git \
                              quay.io/swi-infra/git-daemon
        ExecStop=/usr/bin/docker kill %p
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15
    - name: gerrit.service
      command: start
      content: |
        [Unit]
        Description=Gerrit
        After=docker.service data-storage.service glusterfs.service
        Requires=docker.service data-storage.service glusterfs.service

        [Service]
        ExecStart=/tmp/tf-module/scripts/gerrit-mgmt start
        ExecStop=/tmp/tf-module/scripts/gerrit-mgmt stop
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15
    - name: nginx-proxy.service
      command: start
      content: |
        [Unit]
        Description=Nginx proxy
        After=docker.service data-storage.service glusterfs.service
        Requires=docker.service data-storage.service glusterfs.service

        [Service]
        ExecStart=/tmp/tf-module/scripts/proxy-mgmt start nginx-proxy
        ExecStop=/tmp/tf-module/scripts/proxy-mgmt stop nginx-proxy
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15
    - name: letsencrypt.service
      command: start
      content: |
        [Unit]
        Description=Let's encrypt (HTTPS)
        After=docker.service data-storage.service glusterfs.service nginx-proxy.service
        Requires=docker.service data-storage.service glusterfs.service nginx-proxy.service

        [Service]
        ExecStart=/tmp/tf-module/scripts/proxy-mgmt start letsencrypt
        ExecStop=/tmp/tf-module/scripts/proxy-mgmt stop letsencrypt
        Restart=always
        RestartSec=10s
        TimeoutStartSec=0
        TimeoutStopSec=15

  update:
    group: stable
    reboot-strategy: off

write_files:
  - path: /etc/waagent.conf
    permissions: 0644
    owner: root
    content: |
      ResourceDisk.Format=y
      ResourceDisk.EnableSwap=y
  - path: /etc/farm-environment
    permissions: 0644
    owner: root
    content: |
      MACHINE_TYPE=gerrit-master
      FARM_PLATFORM=cloud-azure
      CONFIG_URL=${config_url}
      HOST_HOSTNAME=${gerrit_hostname}
  - path: /etc/gerrit-environment
    permissions: 0644
    owner: root
    content: |
      AUTH_TYPE=${gerrit_auth_type}
      OAUTH_GITHUB_CLIENT_ID=${gerrit_oauth_github_client_id}
      OAUTH_GITHUB_CLIENT_SECRET=${gerrit_oauth_github_client_secret}

